
type TextSample = string; 

const textSample1: TextSample = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lectus mauris ultrices eros in cursus turpis. Vitae purus faucibus ornare suspendisse sed. Tristique senectus et netus et. Eu lobortis elementum nibh tellus. Bibendum ut tristique et egestas. Nunc sed id semper risus in hendrerit gravida rutrum quisque. Et netus et malesuada fames ac turpis egestas. Eu lobortis elementum nibh tellus molestie nunc non blandit. Enim eu turpis egestas pretium aenean. Aliquam faucibus purus in massa tempor nec feugiat nisl. Fringilla ut morbi tincidunt augue.

Pretium nibh ipsum consequat nisl vel. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Tempor nec feugiat nisl pretium fusce id velit. Lectus vestibulum mattis ullamcorper velit sed. At ultrices mi tempus imperdiet. Ullamcorper morbi tincidunt ornare massa eget. Sed risus pretium quam vulputate dignissim suspendisse. Tempor id eu nisl nunc mi. Adipiscing at in tellus integer feugiat. Amet aliquam id diam maecenas ultricies. Sed id semper risus in hendrerit gravida rutrum quisque non. Pellentesque nec nam aliquam sem et tortor consequat id.

Neque sodales ut etiam sit amet nisl purus. Adipiscing commodo elit at imperdiet dui accumsan sit. Sem nulla pharetra diam sit amet nisl suscipit adipiscing. Elit at imperdiet dui accumsan sit amet nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Suspendisse ultrices gravida dictum fusce ut. Dolor sed viverra ipsum nunc. Praesent elementum facilisis leo vel fringilla. Mi eget mauris pharetra et ultrices. Vitae sapien pellentesque habitant morbi tristique senectus et. Vitae auctor eu augue ut lectus arcu bibendum at varius. Risus in hendrerit gravida rutrum quisque. Pellentesque nec nam aliquam sem et tortor consequat. Iaculis eu non diam phasellus vestibulum lorem sed risus. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Vulputate mi sit amet mauris commodo quis imperdiet massa. Tempor id eu nisl nunc mi. Varius morbi enim nunc faucibus a.

Aenean sed adipiscing diam donec adipiscing tristique risus nec. Auctor elit sed vulputate mi sit amet mauris commodo quis. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Laoreet id donec ultrices tincidunt. Habitant morbi tristique senectus et netus et. Id ornare arcu odio ut sem nulla pharetra diam. Id velit ut tortor pretium. Ipsum a arcu cursus vitae. A erat nam at lectus urna. Senectus et netus et malesuada fames ac. Sit amet est placerat in egestas erat imperdiet sed euismod. Sit amet mattis vulputate enim. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Massa tincidunt dui ut ornare lectus sit amet est. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. At elementum eu facilisis sed. Nunc sed velit dignissim sodales. At consectetur lorem donec massa sapien faucibus et molestie ac. Leo vel orci porta non pulvinar neque laoreet suspendisse.

Nunc consequat interdum varius sit amet mattis vulputate enim nulla. Rutrum tellus pellentesque eu tincidunt tortor. Diam quam nulla porttitor massa id neque aliquam. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Euismod elementum nisi quis eleifend. Augue ut lectus arcu bibendum at. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Cursus risus at ultrices mi tempus. Viverra vitae congue eu consequat ac felis. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius sit. Curabitur vitae nunc sed velit dignissim sodales. Odio pellentesque diam volutpat commodo sed. Eget duis at tellus at urna condimentum. Nibh tortor id aliquet lectus proin nibh nisl condimentum id. Massa placerat duis ultricies lacus sed turpis tincidunt. Enim eu turpis egestas pretium aenean pharetra magna ac. Ac ut consequat semper viverra nam libero justo laoreet. Non quam lacus suspendisse faucibus interdum posuere lorem.

Id consectetur purus ut faucibus pulvinar elementum integer enim. Ipsum faucibus vitae aliquet nec ullamcorper sit. Integer eget aliquet nibh praesent tristique magna. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Etiam tempor orci eu lobortis elementum nibh tellus. Magna sit amet purus gravida quis blandit turpis. Quam lacus suspendisse faucibus interdum. Facilisis mauris sit amet massa vitae tortor condimentum lacinia. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Magna fringilla urna porttitor rhoncus dolor. Ut venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Velit scelerisque in dictum non consectetur a erat. Ullamcorper a lacus vestibulum sed. Pharetra diam sit amet nisl suscipit. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl vel.

Cursus metus aliquam eleifend mi in. Non arcu risus quis varius. Scelerisque felis imperdiet proin fermentum leo vel orci. Mi eget mauris pharetra et ultrices. Pharetra et ultrices neque ornare aenean. Metus vulputate eu scelerisque felis imperdiet proin. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Eget nullam non nisi est sit amet facilisis. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Hendrerit dolor magna eget est lorem. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Nisl tincidunt eget nullam non nisi est sit amet. Egestas sed sed risus pretium.

Congue nisi vitae suscipit tellus mauris a diam maecenas. Velit aliquet sagittis id consectetur purus ut faucibus. Nulla malesuada pellentesque elit eget gravida cum. Luctus accumsan tortor posuere ac ut consequat semper viverra. Tincidunt nunc pulvinar sapien et ligula ullamcorper. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Orci sagittis eu volutpat odio facilisis mauris. Posuere lorem ipsum dolor sit amet. Tristique nulla aliquet enim tortor at auctor. Sit amet dictum sit amet justo donec enim diam vulputate. Proin sagittis nisl rhoncus mattis rhoncus urna.

Justo donec enim diam vulputate ut pharetra sit. Aliquet enim tortor at auctor urna. Enim sed faucibus turpis in eu mi bibendum neque egestas. Non enim praesent elementum facilisis leo vel. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Fames ac turpis egestas maecenas pharetra. Tempus quam pellentesque nec nam aliquam sem et tortor. Amet tellus cras adipiscing enim eu. Neque convallis a cras semper auctor neque vitae. Turpis egestas maecenas pharetra convallis posuere.

Et malesuada fames ac turpis egestas maecenas pharetra. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Quis ipsum suspendisse ultrices gravida dictum fusce. Augue ut lectus arcu bibendum at varius vel pharetra vel. Magna fringilla urna porttitor rhoncus dolor purus non. Massa ultricies mi quis hendrerit. Nulla posuere sollicitudin aliquam ultrices. Id velit ut tortor pretium viverra suspendisse potenti. Magna fringilla urna porttitor rhoncus dolor. Quam nulla porttitor massa id neque aliquam. Netus et malesuada fames ac turpis egestas sed. Diam volutpat commodo sed egestas egestas. Erat nam at lectus urna duis convallis convallis. Libero justo laoreet sit amet cursus sit. Ut sem nulla pharetra diam. Suspendisse sed nisi lacus sed viverra tellus in hac habitasse. Cursus euismod quis viverra nibh cras pulvinar mattis nunc. Blandit libero volutpat sed cras. Id eu nisl nunc mi ipsum.

Mus mauris vitae ultricies leo integer malesuada nunc vel. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Et odio pellentesque diam volutpat commodo sed egestas. Platea dictumst quisque sagittis purus. Lectus sit amet est placerat in egestas. In iaculis nunc sed augue lacus viverra vitae congue. Sit amet massa vitae tortor condimentum lacinia quis vel eros. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Non diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Nec nam aliquam sem et tortor. Aliquet nibh praesent tristique magna sit amet purus gravida. Duis ultricies lacus sed turpis tincidunt id aliquet. Sit amet mauris commodo quis. Morbi non arcu risus quis varius quam quisque. Aliquam nulla facilisi cras fermentum. Ut consequat semper viverra nam libero justo laoreet sit amet. A iaculis at erat pellentesque adipiscing commodo elit at. Tempor orci dapibus ultrices in iaculis nunc sed augue.

Eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Pretium lectus quam id leo in. Sit amet mauris commodo quis. Interdum velit laoreet id donec ultrices tincidunt arcu non. Purus ut faucibus pulvinar elementum. Bibendum neque egestas congue quisque egestas diam. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Elit duis tristique sollicitudin nibh sit amet commodo nulla facilisi. In hendrerit gravida rutrum quisque non tellus orci. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Id leo in vitae turpis massa sed elementum tempus. Pellentesque habitant morbi tristique senectus et. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Convallis aenean et tortor at risus viverra. Nunc congue nisi vitae suscipit tellus mauris a diam. Purus faucibus ornare suspendisse sed nisi lacus sed viverra. Cras sed felis eget velit aliquet.

Feugiat nisl pretium fusce id velit ut. Amet purus gravida quis blandit turpis cursus in hac. At consectetur lorem donec massa sapien faucibus. Sit amet est placerat in egestas erat imperdiet sed. Tortor at risus viverra adipiscing at in tellus integer feugiat. Cursus sit amet dictum sit amet justo. Sit amet consectetur adipiscing elit duis tristique. In cursus turpis massa tincidunt dui ut ornare lectus sit. Euismod quis viverra nibh cras pulvinar. Phasellus egestas tellus rutrum tellus pellentesque eu. Mauris sit amet massa vitae tortor condimentum lacinia. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Donec et odio pellentesque diam volutpat commodo sed. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Maecenas pharetra convallis posuere morbi leo urna molestie.

Risus nec feugiat in fermentum posuere. Et netus et malesuada fames ac turpis egestas sed tempus. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh sed. Aenean euismod elementum nisi quis eleifend quam adipiscing. Ut consequat semper viverra nam libero justo laoreet sit amet. Vivamus at augue eget arcu dictum varius. Est placerat in egestas erat imperdiet sed euismod nisi. Sagittis orci a scelerisque purus semper eget duis at. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Risus ultricies tristique nulla aliquet enim tortor at. Tellus in metus vulputate eu.

Massa id neque aliquam vestibulum morbi blandit. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Sed id semper risus in hendrerit gravida rutrum. Augue interdum velit euismod in pellentesque massa placerat duis. At risus viverra adipiscing at in tellus integer feugiat. Nunc non blandit massa enim. Egestas congue quisque egestas diam in arcu. Amet venenatis urna cursus eget nunc scelerisque. In tellus integer feugiat scelerisque varius morbi enim. Adipiscing bibendum est ultricies integer quis auctor elit sed. Tincidunt arcu non sodales neque sodales ut etiam. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum integer. Eu feugiat pretium nibh ipsum. Lectus magna fringilla urna porttitor rhoncus dolor purus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut. Elit duis tristique sollicitudin nibh sit amet commodo. Tortor at risus viverra adipiscing at in tellus integer.

Convallis tellus id interdum velit laoreet. Fermentum leo vel orci porta non pulvinar neque laoreet suspendisse. At varius vel pharetra vel turpis nunc. Sit amet volutpat consequat mauris nunc congue. Amet cursus sit amet dictum sit amet justo donec enim. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Elementum curabitur vitae nunc sed velit dignissim sodales ut eu. Varius quam quisque id diam vel quam elementum pulvinar. Eget nunc scelerisque viverra mauris in aliquam sem fringilla. Nulla facilisi nullam vehicula ipsum a. Et pharetra pharetra massa massa ultricies mi quis hendrerit. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis.

Enim ut sem viverra aliquet eget sit amet. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Eget mauris pharetra et ultrices neque ornare aenean. Mi ipsum faucibus vitae aliquet nec. Vulputate mi sit amet mauris commodo quis imperdiet massa. Ut tellus elementum sagittis vitae et leo. Vitae et leo duis ut diam quam nulla. At augue eget arcu dictum varius duis. Facilisis leo vel fringilla est ullamcorper eget nulla. Felis eget nunc lobortis mattis aliquam faucibus purus in massa. Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus. Fringilla ut morbi tincidunt augue interdum velit euismod. Eget sit amet tellus cras adipiscing enim eu. Eget gravida cum sociis natoque penatibus et magnis.

Vitae congue mauris rhoncus aenean vel elit. Sed tempus urna et pharetra pharetra massa massa ultricies. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Mauris in aliquam sem fringilla ut morbi tincidunt augue interdum. Volutpat est velit egestas dui id ornare. Senectus et netus et malesuada fames ac. Amet cursus sit amet dictum sit amet justo donec. Nunc mattis enim ut tellus elementum sagittis vitae. Etiam erat velit scelerisque in. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Netus et malesuada fames ac turpis egestas sed tempus urna. In massa tempor nec feugiat nisl pretium fusce. Posuere lorem ipsum dolor sit. Sit amet massa vitae tortor condimentum. Leo integer malesuada nunc vel risus commodo viverra. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Nullam eget felis eget nunc lobortis.

At ultrices mi tempus imperdiet nulla malesuada. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Nam libero justo laoreet sit amet cursus sit. Mollis aliquam ut porttitor leo a diam. Lorem ipsum dolor sit amet. Nunc non blandit massa enim nec dui nunc. Adipiscing diam donec adipiscing tristique risus nec. Ipsum dolor sit amet consectetur adipiscing. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien.

Sit amet mauris commodo quis imperdiet. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Dolor magna eget est lorem ipsum dolor sit. Imperdiet proin fermentum leo vel orci. Neque vitae tempus quam pellentesque nec nam aliquam sem. Blandit aliquam etiam erat velit. Nisi quis eleifend quam adipiscing. Dictumst quisque sagittis purus sit amet volutpat. Ac turpis egestas integer eget aliquet nibh. Varius sit amet mattis vulputate enim. Mi proin sed libero enim sed faucibus turpis in eu. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Vestibulum lectus mauris ultrices eros. Enim nec dui nunc mattis enim ut. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Sem nulla pharetra diam sit. Convallis tellus id interdum velit laoreet id donec. Id faucibus nisl tincidunt eget. Nulla facilisi etiam dignissim diam quis enim.

Viverra orci sagittis eu volutpat odio facilisis mauris sit amet. Donec enim diam vulputate ut pharetra sit amet. Rutrum quisque non tellus orci ac auctor. Aliquet sagittis id consectetur purus. Mauris commodo quis imperdiet massa tincidunt nunc. Odio tempor orci dapibus ultrices in iaculis. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Cras tincidunt lobortis feugiat vivamus at. Felis eget nunc lobortis mattis aliquam faucibus purus in. Viverra ipsum nunc aliquet bibendum. Porttitor rhoncus dolor purus non enim. Pulvinar neque laoreet suspendisse interdum consectetur. Non diam phasellus vestibulum lorem. Diam sit amet nisl suscipit adipiscing. Tristique senectus et netus et malesuada fames ac turpis egestas. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec.

Porttitor massa id neque aliquam vestibulum. Quis eleifend quam adipiscing vitae. Pellentesque nec nam aliquam sem et tortor. Posuere ac ut consequat semper. Est velit egestas dui id ornare arcu odio. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Tincidunt praesent semper feugiat nibh sed pulvinar. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Bibendum neque egestas congue quisque egestas diam in arcu cursus. Ultricies integer quis auctor elit sed vulputate.

Feugiat in ante metus dictum at tempor. Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Ac tortor dignissim convallis aenean. Quam vulputate dignissim suspendisse in est ante in nibh. Nisl vel pretium lectus quam id leo in vitae. Sit amet luctus venenatis lectus magna fringilla urna. Aliquet nec ullamcorper sit amet risus. Quam id leo in vitae turpis. Nunc mattis enim ut tellus elementum. Diam vulputate ut pharetra sit amet. Sed odio morbi quis commodo odio aenean sed. At lectus urna duis convallis convallis tellus id interdum. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. In aliquam sem fringilla ut morbi.

Aliquam nulla facilisi cras fermentum. Purus sit amet luctus venenatis lectus magna. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Massa sapien faucibus et molestie. Ultrices in iaculis nunc sed augue lacus. Maecenas pharetra convallis posuere morbi. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Magna fermentum iaculis eu non diam. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Augue ut lectus arcu bibendum at varius vel pharetra. Viverra orci sagittis eu volutpat odio facilisis mauris sit amet. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Convallis posuere morbi leo urna molestie at elementum. Eleifend mi in nulla posuere. Maecenas pharetra convallis posuere morbi leo urna. Ornare quam viverra orci sagittis eu volutpat odio. Tempus egestas sed sed risus pretium quam. Ac orci phasellus egestas tellus. Id semper risus in hendrerit gravida rutrum quisque non.

Urna cursus eget nunc scelerisque viverra. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Feugiat nibh sed pulvinar proin. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Et molestie ac feugiat sed lectus. Et pharetra pharetra massa massa ultricies mi. Viverra suspendisse potenti nullam ac tortor vitae. Vitae justo eget magna fermentum. Integer enim neque volutpat ac tincidunt vitae semper quis lectus. Aliquam faucibus purus in massa tempor nec feugiat nisl pretium. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum.`;

const textSample2 = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`;

export default {
    textSample1,
    textSample2
}