
const DEFAULT_NAME              = 'Async'

const DEFAULT_ROOT_TAG          = 'div'
const DEFAULT_SUBCOMPONENT_TAG  = 'span'


const DEFAULT_IDLE_TAG          = DEFAULT_SUBCOMPONENT_TAG
const DEFAULT_RESOLVED_TAG      = DEFAULT_SUBCOMPONENT_TAG
const DEFAULT_REJECTED_TAG      = DEFAULT_SUBCOMPONENT_TAG
const DEFAULT_AWAITING_TAG      = DEFAULT_SUBCOMPONENT_TAG

export {
    DEFAULT_NAME,
    DEFAULT_ROOT_TAG,
    DEFAULT_IDLE_TAG,
    DEFAULT_RESOLVED_TAG,
    DEFAULT_REJECTED_TAG,
    DEFAULT_AWAITING_TAG
}