import { SelectableSection } from '../Select/interfaces'
import { StarIcon } from '@radix-ui/react-icons'

const simpleUnits = [
    'acre', 
    'bit',
    'byte', 
    'celsius', 
    'centimeter', 
    'day', 
    'degree', 
    'farenheit', 
    'fluid-ounce', 
    'foot',
    'gallon',
    'gigabit', 
    'gigabyte', 
    'gram', 
    'hectare', 
    'hour', 
    'inch', 
    'kilobit', 
    'kilobyte', 
    'kilogram', 
    'kilomitre', 
    'litre', 
    'megabit', 
    'megabyte', 
    'meter', 
    'mile', 
    'mile-scandinavian', 
    'milliliter',
    'millimeter', 
    'millisecond',
    'minute', 
    'month', 
    'ounce',
    'percent', 
    'petabyte',
    'pound', 
    'second', 
    'stone', 
    'terabit', 
    'terabyte', 
    'week', 
    'yard',
    'year'
]