import {
    theme as whiteTheme, blackTheme,
    yellowThemeLight, yellowThemeDark,
    amberThemeLight, amberThemeDark,
    orangeThemeLight, orangeThemeDark,
    tomatoThemeLight, tomatoThemeDark,
    redThemeLight, redThemeDark,
    crimsonThemeLight, crimsonThemeDark,
    violetThemeLight, violetThemeDark,
    grassThemeLight, grassThemeDark,
    skyThemeLight, skyThemeDark,
    indigoThemeLight, indigoThemeDark,
    purpleThemeLight, purpleThemeDark,
    blueThemeLight, blueThemeDark,
    cyanThemeLight, cyanThemeDark,
    tealThemeLight, tealThemeDark,
    pinkThemeLight, pinkThemeDark,
    mintThemeLight, mintThemeDark,
    limeThemeLight, limeThemeDark,
    greenThemeLight, greenThemeDark,
    plumThemeLight, plumThemeDark,
    brownThemeLight, brownThemeDark,
    goldThemeLight,  goldThemeDark,
    slateThemeLight, slateThemeDark,
    sageThemeLight, sageThemeDark,
    oliveThemeLight, oliveThemeDark,
    sandThemeLight, sandThemeDark,
    mauveThemeLight, mauveThemeDark,
    bronzeThemeLight, bronzeThemeDark
} from '../stitches.config'
import { ThemeDatum } from '@/interfaces/Themes'

export const darkThemes: ThemeDatum[] = [
    { id: 'default-theme-dark', name: 'Default', className: whiteTheme, color: 'black' },
    { id: 'amber-theme-dark',  name: 'Amber Dark', className: amberThemeDark, color: 'amber' },
    { id: 'yellow-theme-dark',  name: 'Yellow Dark', className: yellowThemeDark, color: 'yellow' }, 
    { id: 'orange-theme-dark',  name: 'Orange Dark', className: orangeThemeDark, color: 'orange' }, 
    { id: 'tomato-theme-dark',  name: 'Tomato Dark', className: tomatoThemeDark, color: 'tomato' }, 
    { id: 'red-theme-dark',  name: 'Red Dark', className: redThemeDark, color: 'red' }, 
    { id: 'crimson-theme-dark', name: 'Crimson Dark', className: crimsonThemeDark, color: 'crimson' }, 
    { id: 'pink-theme-dark', name: 'Pink Dark', className: pinkThemeDark, color: 'pink' },
    { id: 'plum-theme-dark', name: 'Plum Dark', className: plumThemeDark, color: 'plum' },
    { id: 'purple-theme-dark', name: 'Purple Dark', className: purpleThemeDark, color: 'purple' },
    { id: 'indigo-theme-dark', name: 'Indigo Dark', className: indigoThemeDark, color: 'indigo' },
    { id: 'violet-theme-dark',name: 'Violet Dark', className: violetThemeDark, color: 'violet' },
    { id: 'blue-theme-dark', name: 'Blue Dark', className: blueThemeDark, color: 'blue' },
    { id: 'sky-theme-dark',  name: 'Sky Dark', className: skyThemeDark, color: 'sky' },
    { id: 'cyan-theme-dark', name: 'Cyan Dark', className: cyanThemeDark, color: 'cyan' },
    { id: 'teal-theme-dark', name: 'Teal Dark', className: tealThemeDark, color: 'teal' },
    { id: 'mint-theme-dark', name: 'Mint Dark', className: mintThemeDark, color: 'mint' },
    { id: 'lime-theme-dark', name: 'Lime Dark', className: limeThemeDark, color: 'lime' },
    { id: 'green-theme-dark',name: 'Green Dark', className: greenThemeDark, color: 'green' },
    { id: 'grass-theme-dark', name: 'Grass Dark', className: grassThemeDark, color: 'grass' },
    // { id: 'brown-theme-dark', name: 'Brown Dark', className: brownThemeDark, color: 'brown' },
    // { id: 'gold-theme-dark', name: 'Gold Dark', className: goldThemeDark, color: 'gold' },
    // { id: 'bronze-theme-dark',name: 'Bronze Dark', className: bronzeThemeDark, color: 'bronze' },
    // { id: 'slate-theme-dark', name: 'Slate Dark', className: slateThemeDark, color: 'slate' },
    // { id: 'mauve-theme-dark', name: 'Mauve Dark', className: mauveThemeDark, color: 'mauve' },
    // { id: 'sage-theme-dark', name: 'Sage Dark', className: sageThemeDark, color: 'sage' },
    // { id: 'olive-theme-dark', name: 'Olive Dark', className: oliveThemeDark, color: 'olive' },
    // { id: 'sand-theme-dark', name: 'Sand Dark', className: sandThemeDark, color: 'sand' }
];

export const lightThemes: ThemeDatum[] = [
{ id: 'default-theme-light', name: 'Default', className: blackTheme, color: 'white', base: 'rgba(252,252,252)' },
{ id: 'amber-theme-light', name: 'Amber Light', className: amberThemeLight, color: 'amber', base: 'rgba(183,78,0)' },
{ id: 'yellow-theme-light',  name: 'Yellow Light', className: yellowThemeLight, color: 'yellow', base:'rgba(153,103,0)'}, 
{ id: 'orange-theme-light',  name: 'Orange Light', className: orangeThemeLight, color: 'orange', base:'rgba(202,57,0)' }, 
{ id: 'tomato-theme-light',  name: 'Tomato Light', className: tomatoThemeLight, color: 'tomato', base: 'rgba(208,0,0)' }, 
{ id: 'red-theme-light',  name: 'Red Light', className: redThemeLight, color: 'red', base: 'rgba(221,0,26)' }, 
{ id: 'crimson-theme-light',name: 'Crimson Light', className: crimsonThemeLight, color: 'crimson',base: 'rgba(229,0,95)'},
{ id: 'pink-theme-light', name: 'Pink Light', className: pinkThemeLight, color: 'pink', base: 'rgba(223,0,138)' },
{ id: 'plum-theme-light', name: 'Plum Light', className: plumThemeLight, color: 'plum', base: 'rgba(150,0,151)' },
{ id: 'purple-theme-light', name: 'Purple Light', className: purpleThemeLight, color: 'purple', base: 'rgba(135,0,177)' },
{ id: 'violet-theme-light', name: 'Violet Light', className: violetThemeLight, color: 'violet', base: 'rgba(97,46,177)' },
{ id: 'indigo-theme-light', name: 'Indigo Light', className: indigoThemeLight, color: 'indigo', base: 'rgba(60,67,181)' },
{ id: 'blue-theme-light', name: 'Blue Light', className: blueThemeLight, color: 'blue', base: 'rgba(10,93,223)' },
{ id: 'sky-theme-light',  name: 'Sky Light', className: skyThemeLight, color: 'sky', base: 'rgba(0,120,164)' },
{ id: 'mint-theme-light', name: 'Mint Light', className: mintThemeLight, color: 'mint', base: 'rgba(45,225,195)' },
{ id: 'cyan-theme-light', name: 'Cyan Light', className: cyanThemeLight, color: 'cyan', base: 'rgba(0,151,182)' },
{ id: 'teal-theme-light', name: 'Teal Light', className: tealThemeLight, color: 'teal', base: 'rgba(0,127,113)' },
{ id: 'green-theme-light',name: 'Green Light', className: greenThemeLight, color: 'green', base: 'rgba(0,128,79)' },
{ id: 'grass-theme-light',name: 'Grass Light', className: grassThemeLight, color: 'grass', base: 'rgba(0,131,59)' },
{ id: 'lime-theme-light', name: 'Lime Light', className: limeThemeLight, color: 'lime', base: 'rgba(92,125,1)' },
// { id: 'brown-theme-light',name: 'Brown Light', className: brownThemeLight, color: 'brown' },
// { id: 'gold-theme-light', name: 'Gold Light', className: goldThemeLight, color: 'gold' },
// { id: 'bronze-theme-light',name: 'Bronze Light', className: bronzeThemeLight, color: 'bronze' },
// { id: 'slate-theme-light', name: 'Slate Light', className: slateThemeLight, color: 'slate' },
// { id: 'mauve-theme-light', name: 'Mauve Light', className: mauveThemeLight, color: 'mauve' },
// { id: 'sage-theme-light', name: 'Sage Light', className: sageThemeLight, color: 'sage' },
// { id: 'olive-theme-light', name: 'Olive Light', className: oliveThemeLight, color: 'olive' },
// { id: 'sand-theme-light', name: 'Sand Light', className: sandThemeLight, color: 'sand' }
]

const allThemes: ThemeDatum[] = [ ...lightThemes, ...darkThemes ]
export default allThemes
